spring:
  application:
    name: restapi
  datasource:
    name: demo05
    url: jdbc:mysql://localhost:3306/demo05
    username: provision
    password: smg123
#  security:
#    user:
#      name: admin
#      password: 123
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.mayanan.restapi.bean

server:
  port: 8081

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true
